"""inicial

Revision ID: 6f02bcf411db
Revises: 
Create Date: 2026-09-18 18:47:51.229154

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6f02bcf411db'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingest_failures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_failures_source_ref'), 'ingest_failures', ['source_ref'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('artist_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.BigInteger(), nullable=False),
    sa.Column('audio_path', sa.Text(), nullable=False),
    sa.Column('top_genre', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_artist_id'), 'tracks', ['artist_id'], unique=False)
    op.create_index(op.f('ix_tracks_top_genre'), 'tracks', ['top_genre'], unique=False)
    op.create_table('features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Text(), nullable=False),
    sa.Column('spec_fingerprint', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'spec_fingerprint', name='uq_feature_track_spec')
    )
    op.create_index(op.f('ix_features_spec_fingerprint'), 'features', ['spec_fingerprint'], unique=False)
    op.create_index(op.f('ix_features_track_id'), 'features', ['track_id'], unique=False)
    op.create_table('track_genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Text(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'genre_id', name='uq_track_genre')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_genres')
    op.drop_index(op.f('ix_features_track_id'), table_name='features')
    op.drop_index(op.f('ix_features_spec_fingerprint'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_tracks_top_genre'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_artist_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_ingest_failures_source_ref'), table_name='ingest_failures')
    op.drop_table('ingest_failures')
    op.drop_table('genres')
    op.drop_table('artists')
    # ### end Alembic commands ###
